---
name: codecov
'on':
  push:
    branches:
      - main
jobs:
  codecov:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true
      - run: bundle exec rake
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/.resultset.json
          flags: unittests
          name: codecov-coverage
