---
name: typos
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
