---
name: yamllint
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  yamllint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
